# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates

version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      # Set to minimise the number of chromatic runs.
      rebase-strategy: "disabled"

      ignore:
        # The version of the aws-cdk[-lib] & constructs dependencies should match exactly the version specified by @guardian/cdk
        - dependency-name: 'aws-cdk'
        - dependency-name: 'aws-cdk-lib'
        - dependency-name: 'constructs'
      open-pull-requests-limit: 10
    - package-ecosystem: 'npm'
      directory: '/apps-rendering'
      schedule:
          interval: 'daily'
      labels:
        - "AR Dependency"
      rebase-strategy: "disabled"
      ignore:
        # The version of the aws-cdk[-lib] & constructs dependencies should match exactly the version specified by @guardian/cdk
        - dependency-name: 'aws-cdk'
        - dependency-name: 'aws-cdk-lib'
        - dependency-name: 'constructs'
      open-pull-requests-limit: 7
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
      rebase-strategy: "disabled"
