# yaml-language-server: $schema=./cloudformation.yml
# ^ this setting effectively prevents the redhat.vscode-yaml extension from
# trying (and failing) to validate this against the Cloudformation YAML schema
# @see: https://github.com/redhat-developer/vscode-yaml/issues/245#issuecomment-885803310
AWSTemplateFormatVersion: '2010-09-09'
Description: Frontend rendering service
Parameters:
  Subnets:
    Description: The subnets where rendering instances will run
    Type: List<AWS::EC2::Subnet::Id>
  App:
    Description: Application name
    Type: String
    Default: rendering
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - PROD
      - CODE
    Default: CODE
  Stack:
    Description: Stack name
    Type: String
    Default: frontend
  NotificationAlarmAction:
    Type: CommaDelimitedList
    Description: (Optional) ARN of action to execute when notification alarms change state
    Default: ''
  Backend5XXAlarmThreshold:
    Type: String
    Description: (Optional) Max number of errors before the 5XX alarm is triggered
    Default: '100'
  Backend5XXAlarmPeriod:
    Type: String
    Description: (Optional) Duration in seconds before 5XX alarm is triggered
    Default: '60'
  Backend5XXConsecutivePeriod:
    Type: String
    Description: (Optional) Number of consecutive periods the threshold needs to be reached before 5XX alarm is triggered
    Default: '5'
  InstanceType:
    Type: String
    Description: EC2 Instance Type to use for dotcom-rendering
  AutoscalingGroup:
    Description: Name of the Autoscaling group
    Type: String
  InternalLoadBalancer:
    Description: Id of internal load balancer
    Type: String
  InstanceRole:
    Description: Name of instance role
    Type: String
  ScaleDownPolicy:
    Description: Ref of scale down policy
    Type: AWS::AutoScaling::ScalingPolicy
  ScaleUpPolicy:
    Description: Ref of scale up policy
    Type: AWS::AutoScaling::ScalingPolicy
  # ! These params are not used but should be kept until the migration is finished
  ELKStream:
    Description: name of the kinesis stream to use to send logs to the central ELK stack
    Type: String
  AMI:
    Description: AMI to use for instances
    Type: AWS::EC2::Image::Id

Mappings:
  Constants:
    Stack:
      Value: frontend
    App:
      Value: rendering

Resources:
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: InstanceRole



