stacks: [frontend]
regions: [eu-west-1]
allowedStages:
  - CODE
  - PROD
deployments:
  frontend-cfn:
    type: cloud-formation
    parameters:
      templateStagePaths:
        CODE: DotcomRendering-CODE.template.json
        PROD: DotcomRendering-PROD.template.json
      cloudFormationStackByTags: false
      cloudFormationStackName: rendering
  rendering:
    type: autoscaling
    parameters:
      bucketSsmKey: /account/services/dotcom-artifact.bucket
    dependencies:
      - frontend-static
      - frontend-cfn
  frontend-static:
    type: aws-s3
    parameters:
      bucketSsmKey: /account/services/dotcom-static.bucket
      cacheControl:
        # assets hashed by Webpack
        - pattern: \.[0-9a-f]{20}\.js
          value: public, max-age=315360000, immutable
        - pattern: .*
          value: max-age=3600
      prefixStack: false
      publicReadAcl: false
