stacks: [frontend]
regions: [eu-west-1]
allowedStages:
  - CODE
  - PROD
deployments:
  frontend-cfn:
    type: cloud-formation
    parameters:
      templateStagePaths:
        CODE: DotcomRendering-CODE.template.json
        PROD: DotcomRendering-PROD.template.json
      templateParameters:
        VpcId: "/account/vpc/primary/id"
      cloudFormationStackByTags: false
      cloudFormationStackName: rendering
      templateStageParameters:
        CODE:
          InstanceType: t4g.micro
        PROD:
          InstanceType: t4g.small
      amiParametersToTags:
        AMI:
          # Keep the Node version in sync with `.nvmrc`
          Recipe: dotcom-rendering-ARM-jammy-node-18.17.0
          BuiltBy: amigo
          AmigoStage: PROD
  rendering:
    type: autoscaling
    parameters:
      bucketSsmKey: /account/services/dotcom-artifact.bucket
    dependencies:
      - frontend-static
      - frontend-cfn
  frontend-static:
    type: aws-s3
    parameters:
	  asgMigrationInProgress: true
      bucketSsmKey: /account/services/dotcom-static.bucket
      cacheControl: public, max-age=315360000, immutable
      prefixStack: false
      publicReadAcl: false
