stacks: [frontend]
regions: [eu-west-1]
allowedStages:
  - CODE
  - PROD
deployments:
  frontend-cfn:
    type: cloud-formation
    parameters:
      templateStagePaths:
        CODE: DotcomRendering-CODE.template.json
        PROD: DotcomRendering-PROD.template.json
      cloudFormationStackByTags: false
      cloudFormationStackName: rendering
  rendering:
    type: autoscaling
    parameters:
      bucketSsmKey: /account/services/dotcom-artifact.bucket
    dependencies:
      - frontend-static
      - frontend-cfn
  frontend-static:
    type: aws-s3
    parameters:
      bucketSsmKey: /account/services/dotcom-static.bucket
      cacheControl:
        - pattern: \/stats\/ # stats file can change on each deploy
          value: max-age=3600 # one hour in seconds
          # assume all other assets are hashed and never change,
          # even though this is not the case–e.g. icons
        - pattern: .*
          value: public, max-age=315360000, immutable # one year in seconds
      prefixStack: false
      publicReadAcl: false
