name: DCR AMP Validation
on:
    push:
        paths-ignore:
            - "apps-rendering/**"
            - "dotcom-rendering/docs/**"

jobs:
    amp_validation:
        name: DCR AMP Validation
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                node-version-file: '.nvmrc'
                cache: 'yarn'

            # Cache npm dependencies using https://github.com/bahmutov/npm-install
            - uses: bahmutov/npm-install@v1

            - name: Validate AMP
              run: make ampValidation
              working-directory: dotcom-rendering
