name: AR CI

on:
  push:
  workflow_dispatch:

# Allow queued workflows to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

# Allow GitHub to request an OIDC JWT ID token, to use with aws-actions/configure-aws-credentials
permissions:
  id-token: write
  contents: read
  pull-requests: write # required by guardian/actions-riff-raff@v4

jobs:
  build:
    name: AR CI
    runs-on: ubuntu-latest

    # Checkout the repository
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node environment
        uses: ./.github/actions/setup-node-env

      # Execute some tasks from the `apps-rendering/package.json` file, using `pnpm`
      - name: Build and package
        working-directory: apps-rendering
        run: |
          pnpm test
          pnpm build:client:prod
          pnpm build:server:prod
          pnpm copy-manifest
          pnpm copy-fonts
          pnpm synth
          zip -j dist/server/mobile-apps-rendering.zip dist/server/*

      - name: AWS Auth
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1
          mask-aws-account-id: true

      - name: Upload to riff-raff
        uses: guardian/actions-riff-raff@v4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          configPath: apps-rendering/riff-raff.yaml
          projectName: Mobile::mobile-apps-rendering
          buildNumberOffset: 27000 # This is the last build number from TeamCity
          contentDirectories: |
            mobile-apps-rendering-cfn:
              - apps-rendering/cdk.out/MobileAppsRendering-CODE.template.json
              - apps-rendering/cdk.out/MobileAppsRendering-PROD.template.json
            mobile-apps-rendering-preview-cfn:
              - apps-rendering/cdk.out/MobileAppsRenderingPreview-CODE.template.json
              - apps-rendering/cdk.out/MobileAppsRenderingPreview-PROD.template.json
            mobile-apps-rendering:
              - apps-rendering/dist/server/mobile-apps-rendering.zip
            mobile-assets:
              - apps-rendering/dist/assets/
