name: AR Validate

on:
    push:
        branches:
            - main
        paths-ignore:
            - "dotcom-rendering/**"
    pull_request:
        branches:
            - main
        paths-ignore:
            - "dotcom-rendering/**"

jobs:
    validate:
        name: AR Validate
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - uses: guardian/actions-setup-node@main

            # Cache npm dependencies using https://github.com/bahmutov/npm-install
            # Root dependencies
            - uses: bahmutov/npm-install@v1

            - uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: node-

            - name: install
              run: npm ci
              working-directory: apps-rendering

            - name: lint
              run: npm run lint
              working-directory: apps-rendering

            - name: test
              run: npm run test
              working-directory: apps-rendering

            - name: compile client
              run: npm run build:client:prod
              working-directory: apps-rendering

            - name: compile server
              run: npm run build:server:prod
              working-directory: apps-rendering
