name: AR Validate

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'dotcom-rendering/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'dotcom-rendering/**'

jobs:
  validate:
    name: AR Validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node environment
        uses: ./.github/actions/setup-node-env

      - name: Lint
        run: yarn lint
        working-directory: apps-rendering

      - name: Test
        run: yarn test
        working-directory: apps-rendering

      - name: Compile client
        run: yarn build:client:prod
        working-directory: apps-rendering

      - name: Compile server
        run: yarn build:server:prod
        working-directory: apps-rendering
