name: DCR Build Check
on:
  push:
    paths-ignore:
      - 'apps-rendering/**'
      - 'dotcom-rendering/docs/**'

jobs:
  build_check:
    name: DCR Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - name: Generate production build
        run: make build
        working-directory: dotcom-rendering

      - name: Validate Build
        run: make buildCheck
        working-directory: dotcom-rendering
