name: DCR Bundle Analyser
on:
  push:
    paths-ignore:
      - 'apps-rendering/**'
      - 'dotcom-rendering/docs/**'
jobs:
  build_check:
    name: DCR Bundle Analyser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - name: Generate production build
        run: make build
        working-directory: dotcom-rendering

      - name: Archive code coverage results for web bundle
        uses: actions/upload-artifact@v3
        with:
          name: bundle-analyser-report
          path: dotcom-rendering/dist/stats/client.web-bundles.html
          if-no-files-found: error
      - name: Archive code coverage results for web legacy bundle
        uses: actions/upload-artifact@v3
        with:
          name: bundle-analyser-report
          path: dotcom-rendering/dist/stats/client.web.legacy-bundles.html
          if-no-files-found: error
      - name: Archive code coverage results for web variant bundle
        uses: actions/upload-artifact@v3
        with:
          name: bundle-analyser-report
          path: dotcom-rendering/dist/stats/client.web.variant-bundles.html
          if-no-files-found: warn # Variant bundle only exists when an active experiment is going on
      - name: Archive code coverage results for apps bundle
        uses: actions/upload-artifact@v3
        with:
          name: bundle-analyser-report
          path: dotcom-rendering/dist/stats/client.apps-bundles.html
          if-no-files-found: error
