name: DCR Bundle Analyser
on:
  push:
    paths-ignore:
      - 'apps-rendering/**'
      - 'dotcom-rendering/docs/**'
jobs:
  build_check:
    name: DCR Bundle Analyser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      # Cache npm dependencies using https://github.com/bahmutov/npm-install
      - uses: bahmutov/npm-install@v1

      - name: Generate production build
        run: make build
        working-directory: dotcom-rendering

      - name: Archive code coverage results for modern bundle
        uses: actions/upload-artifact@v3
        with:
          name: bundle-analyser-report-modern
          path: dotcom-rendering/dist/stats/browser.modern-bundles.html
          if-no-files-found: error
      - name: Archive code coverage results for legacy bundle
        uses: actions/upload-artifact@v3
        with:
          name: bundle-analyser-report-modern
          path: dotcom-rendering/dist/stats/browser.legacy-bundles.html
          if-no-files-found: error
      - name: Archive code coverage results for variant bundle
        uses: actions/upload-artifact@v3
        with:
          name: bundle-analyser-report-variant
          path: dotcom-rendering/dist/stats/browser.variant-bundles.html
          if-no-files-found: warn # Variant bundle only exists when an active experiment is going on
