name: Chromatic 👓

on:
  push:
    branches: [main]
  pull_request:

jobs:
  chromatic:
    name: Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout - On Pull Request
        uses: actions/checkout@v3
        if:  ${{ github.event_name == 'pull_request'}}
        with:
          fetch-depth: 0
          # By default the pull_request event will run on a ephermeral merge commit which simulates a merge between the pull request
          # and the target branch. This can cause issues with Chromatic https://www.chromatic.com/docs/turbosnap#github-pullrequest-triggers
          # Hopefully by checking out the HEAD commit of a PR instead of the merge commit we can avoid some of those issues.
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Checkout - On Push Event
        uses: actions/checkout@v3
        if:  ${{ github.event_name == 'push'}}
        with:
          fetch-depth: 0

      - uses: guardian/actions-setup-node@main

      # Cache npm dependencies using https://github.com/bahmutov/npm-install
      # Root yarn installs all workspaces (root, common, dotcom)
      - uses: bahmutov/npm-install@v1

      - name: Chromatic - Non Dependency PR / main
        uses: chromaui/action@v1
        if: ${{ github.event_name == 'push' || (!contains(github.event.pull_request.labels.*.name, 'dependencies') && github.event.pull_request.user.login != 'dependabot')}}
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          autoAcceptChanges: main
          onlyChanged: true
          untraced: '**/(package**.json|yarn.lock)'

      - name: Chromatic - Dependency PR
        uses: chromaui/action@v1
        if: ${{ github.event_name == 'pull_request' && (contains(github.event.pull_request.labels.*.name, 'dependencies') || github.event.pull_request.user.login == 'dependabot') }}
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          autoAcceptChanges: main
