name: DCR CICD

on:
  push:
    paths-ignore:
      - 'apps-rendering/**'
      - 'dotcom-rendering/docs/**'

jobs:
  container:
    permissions:
      packages: write
    uses: ./.github/workflows/container.yml

  prettier:
    uses: ./.github/workflows/prettier.yml

  jest:
    uses: ./.github/workflows/jest.yml

  lint:
    uses: ./.github/workflows/lint.yml

  node:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno run -A scripts/deno/node.ts

  cypress:
    needs: [container]
    uses: ./.github/workflows/cypress.yml
    with:
      container-image: ${{ needs.container.outputs.container-image }}

  amp:
    needs: [container]
    uses: ./.github/workflows/amp.yml
    with:
      container-image: ${{ needs.container.outputs.container-image }}
