name: DCR CICD

on:
  push:
    paths-ignore:
      - 'apps-rendering/**'
      - 'dotcom-rendering/docs/**'

jobs:
  container:
    permissions:
      packages: write
    uses: ./.github/workflows/container.yml

  prettier:
    uses: ./.github/workflows/prettier.yml

  jest:
    uses: ./.github/workflows/jest.yml

  lint:
    uses: ./.github/workflows/lint.yml

  cypress:
    needs: [container]
    uses: ./.github/workflows/cypress.yml
    with:
      container-image: ${{ needs.container.outputs.container-image }}

  amp:
    needs: [container]
    uses: ./.github/workflows/amp.yml
    with:
      container-image: ${{ needs.container.outputs.container-image }}

  publish-branch:
    if: ${{ ! github.ref == 'refs/heads/main' }}
    permissions:
      id-token: write
      contents: read
    needs: [container, prettier, jest, lint]
    uses: ./.github/workflows/publish.yml
    with:
      container-image: ${{ needs.container.outputs.container-image }}
    secrets:
      GU_RIFF_RAFF_ROLE_ARN: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}

  publish-main:
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      id-token: write
      contents: read
    needs: [container, prettier, jest, lint, cypress, amp]
    uses: ./.github/workflows/publish.yml
    with:
      container-image: ${{ needs.container.outputs.container-image }}
    secrets:
      GU_RIFF_RAFF_ROLE_ARN: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
