name: DCR Compressed Size
on:
  pull_request:
    paths-ignore:
      - "apps-rendering/**"

jobs:
  compressed_size:
    name: DCR Compressed Size
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: guardian/actions-setup-node@main

      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          build-script: build:dcr
