on:
  workflow_dispatch:
    inputs:
      container-image:
        description: 'Image used by DCR service'
        required: true
        type: string

jobs:
  cypress:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        group: [1]
    services:
      DCR:
        image: ${{ inputs.container-image }}
        ports:
          - 9000:9000
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node environment
        uses: ./.github/actions/setup-node-env

      # https://github.com/cypress-io/github-action/issues/1044
      - run: pnpm cypress install
        working-directory: dotcom-rendering

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: dotcom-rendering
          wait-on: 'http://127.0.0.1:9000'
          wait-on-timeout: 30
          browser: chrome
          spec: cypress/e2e/parallel-${{ matrix.group }}/*.js
          install: false
