name: cypress
on: [push]
jobs:
    run:
        runs-on: ubuntu-16.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  start: node scripts/frontend/dev-server
                  wait-on: 'http://localhost:3030'
                  wait-on-timeout: 180
                  quiet: true
                  browser: chrome
