name: DCR Deployment
on:
  push:
    paths-ignore:
      - 'apps-rendering/**'

env:
  # We set NODE_ENV=production globally, this ensures we have consistent yarn installs between jobs
  NODE_ENV: production
  setup_cache_name: ${{github.run_id}}-${{github.run_number}}-setup-output
  build_cache_name: ${{github.run_id}}-${{github.run_number}}-build-output
  cache_path: ./
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: guardian/actions-setup-node@v2.4.1
        with:
          cache: 'yarn'
      - name: Yarn install
        run: yarn --frozen-lockfile
      # Cache the output for use in further jobs
      - uses: actions/cache@v3
        with:
          path: ${{env.cache_path}}
          key: ${{env.setup_cache_name}}
  lint:
    name: lint
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      # Setup Environment
      - uses: actions/cache@v3
        with:
          path: ${{env.cache_path}}
          key: ${{env.setup_cache_name}}
      - name: Extract project
        run: tar -xzf setup-project.tar.gz
      - name: Install Node
        uses: guardian/actions-setup-node@v2.4.1
      # Job Steps
      - name: Lint
        run: make lint
        working-directory: dotcom-rendering
      - name: Stylelint
        run: make stylelint
        working-directory: dotcom-rendering
      - name: Prettier check
        run: yarn prettier:check
        working-directory: dotcom-rendering
  build:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      # Setup Environment
      - uses: actions/cache@v3
        with:
          path: ${{env.cache_path}}
          key: ${{env.setup_cache_name}}
      - name: Install Node
        uses: guardian/actions-setup-node@v2.4.1
      # Job Steps
      - name: Generate production build
        run: make build
        working-directory: dotcom-rendering
      - name: Validate Build
        run: make buildCheck
        working-directory: dotcom-rendering
      # Cache the output for further steps
      - uses: actions/cache@v3
        with:
          path: ${{env.cache_path}}
          key: ${{env.build_cache_name}}
  cypress:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        group: [1, 2, 3, 4, 5, 6]
    steps:
      # Setup Environment
      - uses: actions/cache@v3
        with:
          path: ${{env.cache_path}}
          key: ${{env.build_cache_name}}
      - name: Install Node
        uses: guardian/actions-setup-node@v2.4.1
      # Job Steps
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: make start-ci
          working-directory: dotcom-rendering
          wait-on: 'http://localhost:9000'
          wait-on-timeout: 30
          browser: chrome
          spec: cypress/e2e/parallel-${{ matrix.group }}/*.js

  deploy:
    needs: [build, lint, cypress]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Coming soon..."
