on:
  workflow_call:
    inputs:
      container-image:
        description: 'Image used by DCR service'
        required: true
        type: string

jobs:
  cypress:
    runs-on: ubuntu-20.04
    services:
      DCR:
        image: ${{ inputs.container-image }}
        env:
          NODE_ENV: production
          DISABLE_LOGGING_AND_METRICS: true
        ports:
          - 9000:9000

    strategy:
      fail-fast: false
      matrix:
        group: [1, 2, 3, 4, 5, 6]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: dotcom-rendering
          wait-on: 'http://localhost:9000'
          wait-on-timeout: 30
          browser: chrome
          spec: cypress/e2e/parallel-${{ matrix.group }}/*.js
