name: DCR Deployment
on:
  push:
    paths-ignore:
      - "apps-rendering/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/dcr-test/action.yml
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Coming soon..."



