name: DCR Deployment
on:
  push:
    paths-ignore:
      - "apps-rendering/**"
jobs:
  checkout:
    uses: actions/checkout@v3
  build:
    needs: [checkout]
    runs-on: ubuntu-latest
    uses: ./.github/workflows/dcr-build.yml

  # lint:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Lint
  #       run: make lint
  #       working-directory: dotcom-rendering
  #     - name: Stylelint
  #       run: make stylelint
  #       working-directory: dotcom-rendering
  #     - name: Prettier check
  #       run: yarn prettier:check
  #       working-directory: dotcom-rendering

  # test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Archive code coverage results
  #       uses: actions/upload-artifact@v2
  #       with:
  #           name: bundle-analyser-report
  #           path: dotcom-rendering/dist/browser-bundles.html
  #     - name: Chromatic (TODO)
  #       runs-on: ubuntu-latest
  #       run: echo "TODO..."
  #     - name: Run Jest
  #         run: CI=true yarn test
  #         working-directory: dotcom-rendering
  #     - name: Run check-schema script
  #       run: make check-schema
  #       working-directory: dotcom-rendering
  #     - name: Check typescript
  #       run: yarn tsc
  #       working-directory: dotcom-rendering

  # # Not sure why this is run this way
  # test_cypress:
  #   needs: build
  #   runs-on: ubuntu-20.04
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       group: [1, 2, 3, 4, 5, 6]
  #   steps:
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v4
  #       with:
  #         start: make start-ci
  #         working-directory: dotcom-rendering
  #         wait-on: "http://localhost:9000"
  #         wait-on-timeout: 30
  #         browser: chrome
  #         spec: cypress/e2e/parallel-${{ matrix.group }}/*.js

  deploy:
    # needs: [test, test_cypress]
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Coming soon..."



