on:
  workflow_call:
    inputs:
      container-image:
        description: 'Image used by DCR service'
        required: true
        type: string

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        group:
          - 'http://localhost:9000/Article?url=https://www.theguardian.com/commentisfree/2020/feb/08/hungary-now-for-the-new-right-what-venezuela-once-was-for-the-left#noads'
          - 'http://localhost:9000/Front?url=https://www.theguardian.com/uk'
    services:
      DCR:
        image: ${{ inputs.container-image }}
        env:
          NODE_ENV: production
          DISABLE_LOGGING_AND_METRICS: true
        ports:
          - 9000:9000
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      # Make sure we install dependencies in the root directory
      - uses: bahmutov/npm-install@v1
      - name: Install and run Lighthouse CI
        working-directory: dotcom-rendering
        env:
          LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}
          LHCI_URL: ${{ matrix.group }}
        run: |
          npm install -g puppeteer-core@2.1.0 @lhci/cli@0.10.0
          lhci autorun

      # We're running the deployment workflow on "push" events so that it can be used in both PRs and on the main branch.
      # "push" event doesn't give us access to the usual PR info so we need to use an action in order to obtain that information.
      # This action works by using the Github search API to find a associated PR given a commit ID.
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        if: github.ref != 'refs/heads/main'
        id: PR

      # https://github.com/denoland/setup-deno#latest-stable-for-a-major
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Surface Lighthouse Results
        run: |
          deno run \
            --allow-read \
            --allow-net=api.github.com \
            --allow-env=HOME,GITHUB_TOKEN,ISSUE,LHCI_URL \
            scripts/deno/surface-lighthouse-results.ts
        env:
          LHCI_URL: ${{ matrix.group }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Merge commits will have their corresponding PR as the associated PR.
          # We don't want to surface information to the PR after its been merged, instead it should be surfaced on #4584.
          ISSUE: ${{ github.ref == 'refs/heads/main' && '4584' || steps.PR.outputs.number }}
