name: 🦕 Deno health
on:
  pull_request:
    paths:
      - 'scripts/deno/**'

jobs:
  deno:
    name: 🦕 Deno health
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      # https://github.com/denoland/setup-deno#latest-stable-for-a-major
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Format
        run: deno fmt scripts/deno

      - name: Format
        run: deno lint scripts/deno

      - name: Type-check
        run: deno check scripts/deno/**.ts
