name: 🦕 Deno health
on:
  pull_request:
    paths:
      - 'scripts/deno/**'

jobs:
  deno:
    name: 🦕 Deno health
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1

      - name: Format
        run: deno fmt scripts/deno

      - name: Format
        run: deno lint scripts/deno

      - name: Type-check
        run: deno check --all scripts/deno/**.ts
