on:
  workflow_call:

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - run: yarn install --immutable

      - name: Run Jest
        run: CI=true yarn test
        working-directory: dotcom-rendering
