on:
  workflow_call:

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node environment
        uses: ./.github/actions/setup-node-env

      - name: Run Jest
        run: CI=true yarn test
        working-directory: dotcom-rendering
