name: DCR jest 🤔
on:
  push:
    paths-ignore:
      - "apps-rendering/**"

jobs:
  jest:
    name: DCR Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: guardian/actions-setup-node@main
        with:
          cache: "yarn"

			- name: Install
        run: yarn

      - name: Run Jest
        run: CI=true yarn test
        working-directory: dotcom-rendering
