name: DCR Run Lighthouse CI

on:
  workflow_call:
    inputs:
      container-image:
        description: 'Image used by DCR service'
        required: true
        type: string

jobs:
  lhci:
    name: DCR Lighthouse
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        group:
          - 'http://localhost:9000/Article/https://www.theguardian.com/commentisfree/2020/feb/08/hungary-now-for-the-new-right-what-venezuela-once-was-for-the-left#noads'
          - 'http://localhost:9000/Front/https://www.theguardian.com/uk'
    services:
      DCR:
        image: ${{ inputs.container-image }}
        ports:
          - 9000:9000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node environment
        uses: ./.github/actions/setup-node-env

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: ${{ matrix.group }}
          uploadArtifacts: true # save results as an action artifacts
