name: DCR Run Lighthouse CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'apps-rendering/**'
      - 'dotcom-rendering/docs/**'

  # We need to run on "pull_request" to get the PR number in the event.
  # When running on "push", we cannot add a comment to a specific PR.
  pull_request:
    #  If/when we compare results to `main`, we should also run on 'reopened'
    types: [opened, synchronize]
    paths:
      - 'dotcom-rendering/**'

jobs:
  lhci:
    name: DCR Lighthouse
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        group:
          - 'http://localhost:9000/Article?url=https://www.theguardian.com/commentisfree/2020/feb/08/hungary-now-for-the-new-right-what-venezuela-once-was-for-the-left#noads'
          - 'http://localhost:9000/Front?url=https://www.theguardian.com/uk'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      # Make sure we install dependencies in the root directory
      - uses: bahmutov/npm-install@v1
      - run: make build
        working-directory: dotcom-rendering
      - name: Install and run Lighthouse CI
        working-directory: dotcom-rendering
        env:
          LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}
          LHCI_URL: ${{ matrix.group }}
        run: |
          npm install -g puppeteer-core@2.1.0 @lhci/cli@0.8.2
          lhci autorun

      - name: Setup deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.21.0

      - name: Surface Lighthouse Results
        run: deno run --no-check --allow-net=api.github.com --allow-env="GITHUB_TOKEN","GITHUB_EVENT_PATH","LHCI_URL" --allow-read scripts/deno/surface-lighthouse-results.ts
        env:
          LHCI_URL: ${{ matrix.group }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
