on:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: make install
        working-directory: dotcom-rendering
      - name: Lint
        run: make lint
        working-directory: dotcom-rendering
      - name: Stylelint
        run: make stylelint
        working-directory: dotcom-rendering

  filenames:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # https://github.com/denoland/setup-deno#latest-stable-for-a-major
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: deno run --allow-read scripts/deno/filenames.ts
