name: DCR lint 🔎
on:
    push:
        paths-ignore:
            - "apps-rendering/**"

jobs:
    lint:
        name: DCR Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.5
            - uses: guardian/actions-setup-node@main

            # Cache npm dependencies using https://github.com/bahmutov/npm-install
            - uses: bahmutov/npm-install@v1

            - name: Install
              run: yarn

            - name: Lint
              run: yarn lint
              working-directory: dotcom-rendering
