name: DCR lint 🔎
on:
  push:
    paths-ignore:
      - "apps-rendering/**"

jobs:
  lint:
    name: DCR Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: make install
        working-directory: dotcom-rendering
      - name: Lint
        run: make lint
        working-directory: dotcom-rendering
      - name: Stylelint
        run: make stylelint
        working-directory: dotcom-rendering
