name: DCR lint 🔎
on:
  push:
    paths-ignore:
      - "apps-rendering/**"

jobs:
  lint:
    name: DCR Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: guardian/actions-setup-node@main
        with:
          cache: "yarn"
      - run: make install
        working-directory: dotcom-rendering
      - name: Lint
        run: make lint
        working-directory: dotcom-rendering
      - name: Stylelint
        run: make stylelint
        working-directory: dotcom-rendering
