name: Percy
on:
  push:
    paths-ignore:
      - "apps-rendering/**"
jobs:
  percy:
    name: Percy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - name: Install cypress
        uses: cypress-io/github-action@v4
        with:
          runTests: false
          start: make start-ci
          working-directory: dotcom-rendering
          wait-on: "http://localhost:9000"
          wait-on-timeout: 30
      - name: Percy Test
        run: npx @percy/cli exec -- cypress run
