on:
  workflow_call:
    inputs:
      container-image:
        description: 'Image used by DCR service'
        required: true
        type: string

jobs:
  playwright:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        group: [1, 2, 3, 4, 5, 6]
    services:
      DCR:
        image: ${{ inputs.container-image }}
        ports:
          - 9000:9000
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps chromium
        working-directory: ./dotcom-rendering

      - name: Run Playwright
        run: yarn playwright test parallel-${{ matrix.group }}
        working-directory: ./dotcom-rendering

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-${{ matrix.group }}
          path: ./dotcom-rendering/playwright-report
          retention-days: 5
