name: ⏰ Scheduled daily jobs
on:
  schedule:
    # Every work day of the week at 08:08
    - cron: '8 8 * * MON-FRI'

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.26.2

      - name: Components Ophan attributes tracker
        run: |
          deno run \
            --no-check=remote \
            --allow-net=www.theguardian.com,api.github.com \
            --allow-env="GITHUB_TOKEN" \
            scripts/deno/ophan-components.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Thrasher tracker
        run: |
          deno run \
            --no-check=remote \
            --allow-net \
            --allow-env="GITHUB_TOKEN" \
            scripts/deno/thrasher-tracker.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: iFrame titles tracker
        run: |
          deno run \
            --no-check=remote \
            --allow-net \
            --allow-env="GITHUB_TOKEN,CAPI_KEY" \
            scripts/deno/iframe-titles.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CAPI_KEY: ${{ secrets.CAPI_KEY }}

      # The peer dependencies script relies on `yarn`
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: DCR peer dependencies tracker
        run: |
          deno run \
            --no-check=remote \
            --allow-net \
            --allow-env="GITHUB_TOKEN" \
            --allow-run=yarn,npm \
            scripts/deno/peer-dependencies.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
