name: DCR Schema Check
on:
  push:
    paths-ignore:
      - 'apps-rendering/**'
      - 'dotcom-rendering/docs/**'

jobs:
  build_check:
    name: DCR Schema Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - name: Run check-schema script
        run: make check-schema
        working-directory: dotcom-rendering
