name: DCR Schema Check
on:
  push:
    paths-ignore:
      - "apps-rendering/**"
      - "dotcom-rendering/docs/**"

jobs:
  build_check:
    name: DCR Schema Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      # Cache npm dependencies using https://github.com/bahmutov/npm-install
      - uses: bahmutov/npm-install@v1

      - name: Run check-schema script
        run: make check-schema
        working-directory: dotcom-rendering
