# This monitors all projects in this repository, beecause the DevX workflow
# passes `--all-projects` to `snyk monitor`
# This will monitor dotcom-rendering, apps-rendering, storybook etc
name: Snyk
on:
    schedule:
        - cron: '0 6 * * *'
    push:
        branches:
            - main
    workflow_dispatch:
permissions:
  contents: read
jobs:
    security:
        uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
        with:
            ORG: guardian-dotcom-n2y
            SKIP_SBT: true
        secrets:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
