name: DCR Stories Check
on:
  push:
    paths-ignore:
      - 'apps-rendering/**'
      - "dotcom-rendering/docs/**"

jobs:
  build_check:
    name: DCR Stories Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node
        uses: guardian/actions-setup-node@main

      # Cache npm dependencies using https://github.com/bahmutov/npm-install
      - uses: bahmutov/npm-install@v1

      - name: Run check-stories script
        run: make check-stories
        working-directory: dotcom-rendering
