name: DCR typescript 🕵‍♀
on:
  push:
    paths-ignore:
      - 'apps-rendering/**'
      - 'dotcom-rendering/docs/**'

jobs:
  typescript:
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'yarn'

      - run: yarn install --immutable

      - name: Check typescript
        run: yarn tsc
        working-directory: dotcom-rendering
