name: DCR typescript 🕵‍♀
on:
    push:
        paths-ignore:
            - "apps-rendering/**"

jobs:
    typescript:
        name: Typescript
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: guardian/actions-setup-node@main

            # Cache npm dependencies using https://github.com/bahmutov/npm-install
            - uses: bahmutov/npm-install@v1

            - name: Install
              run: yarn

            - name: Check typescript
              run: yarn tsc
              working-directory: dotcom-rendering
