name: DCR typescript 🕵‍♀
on:
    push:
        paths-ignore:
            - "apps-rendering/**"
            - "dotcom-rendering/docs/**"

jobs:
    typescript:
        name: Typescript
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version-file: .nvmrc
                cache: 'yarn'

            # Cache npm dependencies using https://github.com/bahmutov/npm-install
            - uses: bahmutov/npm-install@v1

            - name: Check typescript
              run: yarn tsc
              working-directory: dotcom-rendering
